FROM node:20-slim AS base
RUN apt-get update -y && apt-get install -y git openssl
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app

COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml turbo.json tsconfig.base.json ./
COPY apps/executor/package.json apps/executor/package.json
COPY packages/contracts/package.json packages/contracts/package.json

COPY . .
RUN pnpm install --frozen-lockfile=false
RUN pnpm --filter @revealth/executor... build

EXPOSE 4100
CMD ["pnpm", "--filter", "@revealth/executor", "start"]
